
pipeline {
  agent any

  tools {
    jdk '17 (OpenJDK)'
  }

  stages {
    stage('build') {
      steps {
       
          sh "./gradle test jacocoTestReport"
          sh "./gradle build " 
      }
    }
  }
}
